### ISSUE TITLE
Typed Dict - typing_extensions

### ISSUE THREAD

**Issue by lolThinked** [mrtolkien/leaguepedia_parser#11]
Error:
_from typing import TypedDict, Dict, List, Optional
ImportError: cannot import name 'TypedDict'_

Fix: 
`if sys.version_info[0] == 3 and sys.version_info[1] >= 8:
    from typing import TypedDict, Literal
else:
    from typing_extensions import TypedDict, Literal`

**Comment by mrtolkien** [comment]
I do not plan on supporting pre 3.8 versions, there would be other issues as well with my use of the walrus operator in other places.

**Comment by lolThinked** [comment]
Yep. I did notice that after I added a fix for every  import used. My bad.

This is totally amazing though, that you created this🥰

ons. 26. mai 2021, 03:55 skrev Tolki ***@***.***>:
