### ISSUE TITLE
Errors when using get_games

### ISSUE THREAD

**Issue by nau7ic** [mrtolkien/leaguepedia_parser#4]
I get a few errors when i use get_games:

**CBLOL/2015 Season/Split 1** had the following error: invalid literal for int() with base 10: 'Tiebreaker'
**LPL/2014 Season/Spring Playoffs** had the following error: invalid literal for int() with base 10: '3 (Blind Pick)'
**LPL/2015 Season/Spring Playoffs** had the following error: invalid literal for int() with base 10: 'Game3'
**EU LCS/Season 3/Summer Promotion** had the following error: invalid literal for int() with base 10: "&lt;abbr title=&quot;\x7f'&quot;`UNIQ--nowiki-00000000-QINU`&quot;'\x7f&quot;&gt;\x7f'&quot;`UNIQ--nowiki-00000001-QINU`&quot;'\x7f&lt;/abbr&gt;"
**Champions/2013 Season/Winter** had the following error: invalid literal for int() with base 10: '5 (Blind Pick)'
**Champions/2013 Season/Summer** had the following error: invalid literal for int() with base 10: '5 (Blind Pick)'
**Champions/2014 Season/Spring Season** had the following error: invalid literal for int() with base 10: 'Blind Pick'
**Champions/2014 Season/Summer Season** had the following error: invalid literal for int() with base 10: 'Blind Pick'
**Champions/2015 Season/Summer Playoffs** had the following error: invalid literal for int() with base 10: '3 (Blind Pick)'
**Season 3 Korea Regional Finals** had the following error: invalid literal for int() with base 10: '3 (Blind Pick)'
**2015 Season Korea Regional Finals** had the following error: invalid literal for int() with base 10: '5 (Blind Pick)'
**OPL/2015 Season/Split 1 Playoffs** had the following error: invalid literal for int() with base 10: "&lt;abbr title=&quot;\x7f'&quot;`UNIQ--nowiki-00000000-QINU`&quot;'\x7f&quot;&gt;\x7f'&quot;`UNIQ--nowiki-00000001-QINU`&quot;'\x7f*&lt;/abbr&gt;"
**2014 GPL Summer** had the following error: invalid literal for int() with base 10: 'Blind Pick'

**Comment by nau7ic** [comment]
i'm using Python 3.8.5 and leaguepedia-parser 1.0a11

**Comment by mrtolkien** [comment]
Indeed, I’m trying to cast the game # from Leaguepedia to an integer *but* it seems they can sometimes be strings.

I’ll go see directly with Leaguepedia to see if we can change it and make it integers everywhere.

**Comment by mrtolkien** [comment]
I fixed it by querying `N_GameInMatch` instead of `Gamename` and released it as `1.0`! I’ve been using the alpha for two months and it looked pretty stable.

Don’t hesitate to report any other issues!
