### ISSUE TITLE
get_games() not working on example code

### ISSUE THREAD

**Issue by jeremiahfallin** [mrtolkien/leaguepedia_parser#6]
I just installed leaguepedia_parser and I'm trying to use the example code snippet but `get_games()` isn't returning anything. I've tried a few different tournaments.

![image](https://user-images.githubusercontent.com/18542660/95007218-1475f080-05c2-11eb-8066-7d341ec9fd69.png)

![image](https://user-images.githubusercontent.com/18542660/95007229-38d1cd00-05c2-11eb-94da-b011179e2aa0.png)

This is the code:
```Python
import leaguepedia_parser

# Gets regions names
regions = leaguepedia_parser.get_regions() 

# Gets tournaments in the region, by default only returns primary tournaments
tournaments = leaguepedia_parser.get_tournaments("Korea", year=2020)

# Gets all games for a tournament. Get the name from get_tournaments()
games = leaguepedia_parser.get_games("LCK 2020 Spring")
print(games)
# Gets picks and bans and other details from a game. Get the game object from get_games()
game = leaguepedia_parser.get_game_details(games[0])

# Gets the URL of the team’s logo
logo_url = leaguepedia_parser.get_team_logo('T1')

**Comment by mrtolkien** [comment]
I changed the example code to one working with the new nomenclature.

Also, I recommend installing version `1.0` and posting errors as text, it will be easier to answer!
