### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by FioraL** [mrtolkien/leaguepedia_parser#7]
Hi, I have installed this package, but when I tried to import it in python or Ipython in the command line, they also show that error " cannot import name 'TypedDict' from 'typing' (/Users/a/anaconda3/lib/python3.7/typing.py)"

**Comment by mrtolkien** [comment]
You need python 3.8 or higher

**Comment by mrtolkien** [comment]
I’ve added the required python version in the `setup.py` so it should automatically warn the user if they try to import it on python 3.7.
